# Generated by Django 3.1.7 on 2021-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210601_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_house',
            field=models.DateTimeField(),
        ),
    ]
